server:
  port: 10030

kafka:
  clusters:
    - 192.168.240.8:9092
  batchsize: 16384
  buffermemory: 33554432
  retries: 0

  consumer.bootstrap.servers:
      - 192.168.240.15:2181
  groupId: test1

topic: consumer-tutorial



spring.dubbo:
  application:
    name: kafka-service-dubbo
  registry:
    address: zookeeper://192.168.240.15:2181
  protocol:
    name: dubbo
    port: 20880
  scan: com.bluemoon.kafka.dubbo