server:
  port: 10030

kafka:
  clusters:
    - 127.0.0.1:9092
  batchsize: 16384
  buffermemory: 33554432
  retries: 0

spring.dubbo:
  application:
    name: provider-test
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan: com.bluemoon.kafka.dubbo